export const mensagensGratuitas = [
  "A resposta que você procura virá em breve. Alguém especial está pensando em você.",
  "A resposta que você procura virá em breve. Grandes oportunidades estão se aproximando.",
  "A resposta que você procura virá em breve. Um novo ciclo cheio de luz se inicia.",
  "A resposta que você procura virá em breve. Você está mais forte do que imagina.",
  "A sorte está ao seu lado. Algo incrível está prestes a acontecer.",
  "A sorte está ao seu lado. Seu brilho interior ilumina novos caminhos.",
  "Algo incrível está prestes a acontecer. Alguém especial está pensando em você.",
  "Algo incrível está prestes a acontecer. Novos começos trarão felicidade.",
  "Algo incrível está prestes a acontecer. O equilíbrio está prestes a chegar.",
  "Algo incrível está prestes a acontecer. O momento certo está se aproximando.",
  "Algo incrível está prestes a acontecer. O universo está conspirando a seu favor.",
  "Algo incrível está prestes a acontecer. Seu brilho interior ilumina novos caminhos.",
  "Algo incrível está prestes a acontecer. Seu destino reserva grandes surpresas.",
  "Algo incrível está prestes a acontecer. Você está cercado de boas energias.",
  "Algo inesperado vai te trazer alegria. A resposta que você procura virá em breve.",
  "Algo inesperado vai te trazer alegria. Alguém especial está pensando em você.",
  "Algo inesperado vai te trazer alegria. Confie no seu potencial.",
  "Algo inesperado vai te trazer alegria. Novos começos trarão felicidade.",
  "Algo inesperado vai te trazer alegria. O momento certo está se aproximando.",
  "Algo inesperado vai te trazer alegria. Prepare-se para uma reviravolta positiva.",
  "Algo inesperado vai te trazer alegria. Seu destino reserva grandes surpresas.",
  "Algo inesperado vai te trazer alegria. Sua intuição será sua maior aliada.",
  "Alguém especial está pensando em você. A resposta que você procura virá em breve.",
  "Alguém especial está pensando em você. A sorte está ao seu lado.",
  "Alguém especial está pensando em você. Grandes oportunidades estão se aproximando.",
  "Alguém especial está pensando em você. Seu brilho interior ilumina novos caminhos.",
  "Alguém especial está pensando em você. Seu destino reserva grandes surpresas.",
  "Alguém especial está pensando em você. Um novo ciclo cheio de luz se inicia.",
  "Alguém especial está pensando em você. Você está cercado de boas energias.",
  "Boas notícias estão a caminho. A sorte está ao seu lado.",
  "Boas notícias estão a caminho. Algo inesperado vai te trazer alegria.",
  "Boas notícias estão a caminho. Alguém especial está pensando em você.",
  "Boas notícias estão a caminho. Grandes oportunidades estão se aproximando.",
  "Boas notícias estão a caminho. Novos começos trarão felicidade.",
  "Boas notícias estão a caminho. O equilíbrio está prestes a chegar.",
  "Boas notícias estão a caminho. Prepare-se para uma reviravolta positiva.",
  "Boas notícias estão a caminho. Seu brilho interior ilumina novos caminhos.",
  "Boas notícias estão a caminho. Você está mais forte do que imagina.",
  "Confie no seu potencial. A resposta que você procura virá em breve.",
  "Confie no seu potencial. Algo incrível está prestes a acontecer.",
  "Confie no seu potencial. Grandes oportunidades estão se aproximando.",
  "Confie no seu potencial. O momento certo está se aproximando.",
  "Confie no seu potencial. Seu destino reserva grandes surpresas.",
  "Confie no seu potencial. Sua intuição será sua maior aliada.",
  "Confie no seu potencial. Você está mais forte do que imagina.",
  "Grandes oportunidades estão se aproximando. A resposta que você procura virá em breve.",
  "Grandes oportunidades estão se aproximando. Algo incrível está prestes a acontecer.",
  "Grandes oportunidades estão se aproximando. Algo inesperado vai te trazer alegria.",
  "Grandes oportunidades estão se aproximando. Prepare-se para uma reviravolta positiva.",
  "Grandes oportunidades estão se aproximando. Sua intuição será sua maior aliada.",
  "Grandes oportunidades estão se aproximando. Um novo ciclo cheio de luz se inicia.",
  "Novos começos trarão felicidade. A sorte está ao seu lado.",
  "Novos começos trarão felicidade. O universo está conspirando a seu favor.",
  "O equilíbrio está prestes a chegar. Algo incrível está prestes a acontecer.",
  "O equilíbrio está prestes a chegar. Alguém especial está pensando em você.",
  "O equilíbrio está prestes a chegar. Boas notícias estão a caminho.",
  "O equilíbrio está prestes a chegar. Prepare-se para uma reviravolta positiva.",
  "O equilíbrio está prestes a chegar. Sua intuição será sua maior aliada.",
  "O momento certo está se aproximando. Confie no seu potencial.",
  "O momento certo está se aproximando. Você está mais forte do que imagina.",
  "O universo está conspirando a seu favor. Prepare-se para uma reviravolta positiva.",
  "O universo está conspirando a seu favor. Um novo ciclo cheio de luz se inicia.",
  "Prepare-se para uma reviravolta positiva. A sorte está ao seu lado.",
  "Prepare-se para uma reviravolta positiva. Boas notícias estão a caminho.",
  "Prepare-se para uma reviravolta positiva. Confie no seu potencial.",
  "Seu brilho interior ilumina novos caminhos. Algo incrível está prestes a acontecer.",
  "Seu brilho interior ilumina novos caminhos. O universo está conspirando a seu favor.",
  "Seu brilho interior ilumina novos caminhos. Sua intuição será sua maior aliada.",
  "Seu brilho interior ilumina novos caminhos. Você está no caminho certo.",
  "Seu destino reserva grandes surpresas. A resposta que você procura virá em breve.",
  "Seu destino reserva grandes surpresas. A sorte está ao seu lado.",
  "Seu destino reserva grandes surpresas. O momento certo está se aproximando.",
  "Seu destino reserva grandes surpresas. O universo está conspirando a seu favor.",
  "Seu destino reserva grandes surpresas. Você está cercado de boas energias.",
  "Sua intuição será sua maior aliada. A sorte está ao seu lado.",
  "Sua intuição será sua maior aliada. Alguém especial está pensando em você.",
  "Sua intuição será sua maior aliada. Confie no seu potencial.",
  "Sua intuição será sua maior aliada. Grandes oportunidades estão se aproximando.",
  "Sua intuição será sua maior aliada. Seu brilho interior ilumina novos caminhos.",
  "Sua intuição será sua maior aliada. Um novo ciclo cheio de luz se inicia.",
  "Um novo ciclo cheio de luz se inicia. Alguém especial está pensando em você.",
  "Um novo ciclo cheio de luz se inicia. Confie no seu potencial.",
  "Um novo ciclo cheio de luz se inicia. Grandes oportunidades estão se aproximando.",
  "Um novo ciclo cheio de luz se inicia. Prepare-se para uma reviravolta positiva.",
  "Um novo ciclo cheio de luz se inicia. Você está no caminho certo.",
  "Você está cercado de boas energias. Grandes oportunidades estão se aproximando.",
  "Você está cercado de boas energias. Novos começos trarão felicidade.",
  "Você está cercado de boas energias. Seu destino reserva grandes surpresas.",
  "Você está cercado de boas energias. Você está mais forte do que imagina.",
  "Você está mais forte do que imagina. A resposta que você procura virá em breve.",
  "Você está mais forte do que imagina. Alguém especial está pensando em você.",
  "Você está mais forte do que imagina. Prepare-se para uma reviravolta positiva.",
  "Você está mais forte do que imagina. Sua intuição será sua maior aliada.",
  "Você está no caminho certo. Algo incrível está prestes a acontecer.",
  "Você está no caminho certo. Boas notícias estão a caminho.",
  "Você está no caminho certo. Confie no seu potencial.",
  "Você está no caminho certo. Grandes oportunidades estão se aproximando.",
  "Você está no caminho certo. O universo está conspirando a seu favor.",
  "Você está no caminho certo. Você está cercado de boas energias.",
  "Você está no caminho certo. Você está mais forte do que imagina."
];
